//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.qunqun.zhaiqunOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.RoleInfo = new HashSet<RoleInfo>();
            this.UserAction = new HashSet<UserAction>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string UserTrueName { get; set; }
        public bool IsDelete { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
        public virtual ICollection<UserAction> UserAction { get; set; }
    }
}
